### ISSUE TITLE
Need to switch files to see color highlights(happens after saving)

### ISSUE THREAD

**Issue by fluxxus** [QW0101/Brackets-Color-Highlighter#5]
I've been using your extension for the last few months and it was all working fine. Then came two updates in the last month(I think there were two), and I think after the last one, something is broken.

And that something is that I need to switch from my css file to another file, then back again to see the colors highlights. And this happens only after I save the css file.

**Comment by Taraflex** [comment]
Thanks for the issues. I can't reproduce the bug. Can you report an accurate list of your installed plugins and their settings? 

P. S. Sorry for my English.

**Comment by fluxxus** [comment]
@Taraflex Before I report my extensions list, I managed to get the pattern where the bug occurs.

Maybe you can try it yourself.
1. Open some css file > change something, then save, it as all fine.
2. Now switch from css to any other file. Then back to your css file. Change some styles, then save. On my end then the color highlights are gone. 

Tested this behaviour multiple times, it always happens.

p.s. your english is perfectly fine, I am not a english native speaker either.

**Comment by Taraflex** [comment]
@Madebym try install the latest version from url https://github.com/Taraflex/Brackets-Color-Highlighter/archive/master.zip
If the problem is corrected, I will update the extension in the market.

**Comment by fluxxus** [comment]
@Taraflex Seems ok now. I only tried a few times, but it is functioning correctly now!

I'll inform you if maybe the issue pops up again.

Thanks for the quick fix :)
