### ISSUE TITLE
Workflow with color highlighter

### ISSUE THREAD

**Issue by schroef** [QW0101/Brackets-Color-Highlighter#6]
Is the only method to edit the colors by using short cut? WHen i click on the color nothing happens or this intended?

Even though it looks very nice and super usefull

**Comment by Taraflex** [comment]
Hi @schroef 

> WHen i click on the color nothing happens or this intended?
> Even though it looks very nice and super usefull

I don't agree. The standard hot keys (ctrl+e) the most convenient. Thanks for the feedback.
