### ISSUE TITLE
do not  to work with files .php (extensions)

### ISSUE THREAD

**Issue by Small-Develop** [QW0101/Brackets-Color-Highlighter#7]
Thanks for this amazing plugin
It does not seem to work with files with .php extensions
For example if I save a file called simple.php does not color the values of the styles.

<pre style="padding: 8px; background-color: #f7f7f9; border: 1px solid #e1e1e8;"><span style="color: rgb(30, 52, 123);">&lt;html&gt;</span><span style="color: rgb(72, 72, 76);">
    </span><span style="color: rgb(30, 52, 123);">&lt;head&gt;</span><span style="color: rgb(72, 72, 76);">
        </span><span style="color: rgb(30, 52, 123);">&lt;style&gt;</span><span style="color: rgb(72, 72, 76);">
            body</span><span style="color: rgb(147, 161, 161);">{</span><span style="color: rgb(72, 72, 76);">
                background</span><span style="color: rgb(147, 161, 161);">:</span><span style="color: rgb(72, 72, 76);"> </span><span style="color: rgb(147, 161, 161);">#fea343;</span><span style="color: rgb(72, 72, 76);">
                color</span><span style="color: rgb(147, 161, 161);">:</span><span style="color: rgb(72, 72, 76);"> </span><span style="color: rgb(147, 161, 161);">#a234fe;</span><span style="color: rgb(72, 72, 76);">
                </span><span style="color: rgb(147, 161, 161);">}</span><span style="color: rgb(72, 72, 76);">
        </span><span style="color: rgb(30, 52, 123);">&lt;/style&gt;</span><span style="color: rgb(72, 72, 76);">         
    </span><span style="color: rgb(30, 52, 123);">&lt;/head&gt;</span><span style="color: rgb(72, 72, 76);">
    </span><span style="color: rgb(30, 52, 123);">&lt;body&gt;</span><span style="color: rgb(72, 72, 76);">
         </span><span style="color: rgb(147, 161, 161);">&lt;?</span><span style="color: rgb(72, 72, 76);">php
            echo </span><span style="color: rgb(221, 17, 68);">"¡Hello,  script in PHP!"</span><span style="color: rgb(147, 161, 161);">;</span><span style="color: rgb(72, 72, 76);">
        </span><span style="color: rgb(147, 161, 161);">?&gt;</span><span style="color: rgb(72, 72, 76);">
    </span><span style="color: rgb(30, 52, 123);">&lt;/body&gt;</span><span style="color: rgb(72, 72, 76);">
</span><span style="color: rgb(30, 52, 123);">&lt;/html&gt;</span></pre>
note: in .html extensions work fine. 

How to make it work with the extension. Php
Thanks

**Comment by Small-Develop** [comment]
<html>
    <head>
        <style>
            body{
                background: #fea343;
                color: #a234fe;
                }
        </style>         
    </head>
    <body>
         <?php
            echo "¡Hello,  script in PHP!";
        ?>
    </body>
</html>

**Comment by Small-Develop** [comment]
this is code 
https://paste.ofcode.org/VyMRucvku9SnTxYqzszdvA

**Comment by Taraflex** [comment]
Fixed in r1.2.2
